### ISSUE TITLE
Error: Couldn't find constructor 'JSExport' from element_embedding_demo

### ISSUE THREAD

**Issue by ninjatang07** [flutter/samples#1649]
I cloned the sample code from element_embedding_demo repo - https://github.com/flutter/samples/tree/main/experimental/element_embedding_demo. 

I got this error when starting the code

`Error: Couldn't find constructor 'JSExport'.
`

Here is my pubsec.yaml 

```
name: element_embedding_demo
description: A small app to be embedded into a HTML element (see web/index.html)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  js: ^0.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dash.png
```
